### ISSUE TITLE
Needs platform abstraction layer / VM

### ISSUE THREAD

**Issue by JayFoxRox** [JayFoxRox/Lindbergh-Emulator#4]
Currently the emulator needs a rather specific version of Linux and set of libraries.

We should be backing up the SEGA open source area (if it still exists) and figure out the library versions used by each game.
Afterwards a VM image can be created.

Due to the HLE / Wrapper approach it's probably best to just use something like virt-io to pass GL to the host (Virtualbox has this feature internally as far as I know; it should be considered / reviewed).
Wether baseboard and other emulation should be moved to the host is not decided yet either.

**Comment by ghost** [comment]
It doesn't exist anymore

**Comment by JayFoxRox** [comment]
The GPL says the offer must be valid while they still provide replacement parts.
See: http://www.segaarcade.com/arcade-game-technical-support/supported-hardware.html

Games can even still be ordered. ~~Someone should send them an email asking for said GPL files as the link provided in the manuals is not working anymore.~~ E-Mail sent (on 8th of Oct. 2017)

**Comment by JayFoxRox** [comment]
Got a reply from ...@sega.co.uk:

> Lindbergh is no longer supported by Sega corporation as of January 2017, furthermore the firmware is not open source code.

I did not ask the japanese division yet. However, I don't intend to do so either.
In my opinion the arcade scene keeps messing up far too much with these things.
Working on the Lindbergh stuff has been very frustrating as a result. I highly doubt anyone archived the original open-source files or even library version numbers.

**Comment by ghost** [comment]
I'll give it a try, but I don't have high expectations

**Comment by ghost** [comment]
Ok, sega.jp refuses to answer to people outside Japan (電話、メールともに海外からのお問い合わせは受け付けておりません。), as stated in their website (https://sega.jp/contact).
I tried looking on archive.org, but nothing has been saved.

**Comment by ekianjo** [comment]
I live in Japan and I could help.

On Wednesday, October 11, 2017, darker00 <notifications@github.com> wrote:
> Ok, sega.jp refuses to answer to people outside Japan
(電話、メールともに海外からのお問い合わせは受け付けておりません。), as stated in their website (
https://sega.jp/contact).
> I tried looking on archive.org, but nothing has been saved.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/8becUBBCkYUdZDBIqJ78DolVlzHfegl8R3_lfwJ-L5pAJXJD2dUOyrxx4qf_fVbS1h_WCbFYcwVJtFMBp0MeQ_Ku0mTCftk5AwbZwC2rZv0U3XEflO_7Ssc-FvgWJ-jxg4ND9Yv-RJhsPj5AkS9rR85r_7TZ7A=s0-d-e1-ft#https://github.com/notifications/beacon/ACWMmEX327YQX75gk53JE8rk0twExzJsks5sq43bgaJpZM4Na1AT.gif
>

-- 
Raphael

**Comment by ghost** [comment]
It'd be great! you should ask if they can still provide the content of http://amproduct-softlicense.sega.jp/

**Comment by ScapeGoat43** [comment]
so how is the progress?

**Comment by ghost** [comment]
Nothing new at the moment as far as I know.
In synthesis no one is working on this wrapper; Jay has too many projects to follow and I tried to work a bit on it but I've other personal matters at the moment to take care of (master thesis). More developers would be welcomed ;-)
